apiVersion: v1
kind: Service
metadata:
  name: umserver-h
  labels:
    app: umheadless
spec:
  clusterIP: None
  ports:
    - port: 9000
      name: headless
  selector:
    name: umserver-pod
    app: msr-hello-world
