apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: msr-hello-world
  name: msr-hello-world
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 0
  selector:
    matchLabels:
      app: msr-hello-world
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: msr-hello-world
    spec:
      containers:
        - image: staillansag/msr-hello-world:latest
          imagePullPolicy: Always
          name: msr
          ports:
            - name: metrics
              containerPort: 5555
          volumeMounts:
            - mountPath: "/tmp/license"
              name: licenses
              readOnly: true
          env:
            - name: SERVER_LOCATION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SAG_IS_LICENSE_FILE
              value: /tmp/license/msr-license
            - name: SAG_IS_CONFIG_PROPERTIES
              value: /opt/softwareag/IntegrationServer/application.properties
            - name: DATASOURCE_CLASS
              value: org.postgresql.ds.PGSimpleDataSource
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: environment-secret
                  key: databaseUser
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: environment-secret
                  key: databasePassword
            - name: DB_SERVERNAME
              valueFrom:
                configMapKeyRef:
                  name: environment-config
                  key: databaseServerName
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: environment-config
                  key: databaseServerPort
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: environment-config
                  key: databaseName
            - name: JNDI_ALIAS_PROVIDERURL
              valueFrom:
                configMapKeyRef:
                  name: environment-config
                  key: jndiAliasProviderUrl
            - name: WM_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: environment-config
                  key: wmDatabaseUrl
            - name: WM_DB_DRIVER_ALIAS
              valueFrom:
                configMapKeyRef:
                  name: environment-config
                  key: wmDriverAlias
            - name: WM_DB_USER
              valueFrom:
                secretKeyRef:
                  name: environment-secret
                  key: wmDatabaseUser
            - name: WM_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: environment-secret
                  key: wmDatabasePassword
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: environment-secret
                  key: wmAdminPassword
          resources:
            requests:
              cpu: 300m
              memory: 500Mi
            limits:
              cpu: 500m
              memory: 1000Mi
          livenessProbe:
            tcpSocket:
              port: 5555
            initialDelaySeconds: 180
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 5555
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 24
      volumes:
        - name: licenses
          secret:
            secretName: licenses


