apiVersion: v1
kind: Service
metadata:
  name: msr-hello-world
  namespace: dce
  labels:
    name: msr-hello-world
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5555
  selector:
    app: msr-hello-world

